name: "Purge Azure Classic CDN Endpoint"
description: "Purges the Azure Classic CDN endpoint using `az cdn endpoint purge`"

inputs:
  resource-group:
    description: "Azure resource group name"
    required: true
  profile-name:
    description: "Azure CDN profile name"
    required: true
  endpoint-name:
    description: "Azure CDN endpoint name"
    required: true
  content-paths:
    description: "Space-separated list of content paths to purge"
    default: "/*"

runs:
  using: composite
  steps:
    - name: Purge endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "## Azure CDN Purge" >> $GITHUB_STEP_SUMMARY
          az cdn endpoint purge \
            --resource-group ${{ inputs.resource-group }} \
            --profile-name ${{ inputs.profile-name }} \
            --name ${{ inputs.endpoint-name }} \
            --content-paths ${{ inputs.content-paths }} &&
            echo "Successfully purged CDN: \
              \`${{ inputs.profile-name }}/${{ inputs.endpoint-name }}\`" >> $GITHUB_STEP_SUMMARY ||
            echo "Failed to purge CDN: \
              \`${{ inputs.profile-name }}/${{ inputs.endpoint-name }}\`" >> $GITHUB_STEP_SUMMARY
