name: Setup Node and NPM
description: Installs Node and NPM packages and automatically caches based on package-lock.json.

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci --legacy-peer-deps=true
