name: Setup Node and NPM
description: Installs Node and NPM packages and automatically caches based on package-lock.json.
inputs:
  install-cypress:
    description: 'Whether to install the Cypress binary'
    default: "true"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      if: inputs.install-cypress == 'true'
      uses: cypress-io/github-action@v5
      with:
        install-command: npm ci --legacy-peer-deps=true
        runTests: false

    - name: Install dependencies
      if: inputs.install-cypress != 'true'
      shell: bash
      run: npm ci --legacy-peer-deps=true
