name: Deploy preview app to Azure
description: Deploys preview app to Azure Webapp.
inputs:
  gh-env:
    description: The GitHub branch being deployed.
    required: true
  azure-publish-profile:
    description: Azure publish profile. Pass in secret.
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Upload to Webapp
      if: inputs.gh-env != 'prod'
      uses: azure/webapps-deploy@v2
      with:
        app-name: obamaorg-preview
        publish-profile: ${{ inputs.azure-publish-profile }}
        package: .
        slot-name: ${{ inputs.gh-env }}
    
    - name: Upload to production Webapp
      if: inputs.gh-env == 'prod'
      uses: azure/webapps-deploy@v2
      with:
        app-name: obamaorg-preview
        publish-profile: ${{ inputs.azure-publish-profile }}
        package: .
