name: "Clean-up Directory"
description: "Cleans out old files from directory"

inputs:
  az-storage-account:
    description: "Azure Blob Storage account name"
    required: true
  az-storage-container:
    description: "Azure Blob Storage container name"
    default: "$web"
  file-retention-days:
    description: "How many days of js and css files we should keep"
    default: 10
runs:
  using: composite
  steps:
    - name: Set the delete date
      shell: bash
      run: |
        echo "DELETE_DATE="`date --date='${{inputs.file-retention-days}} day ago' +%F'T'%H:%M'Z'` >> "$GITHUB_ENV"
    - name: Delete old files from previous container
      shell: bash
      run: |
        az storage blob delete-batch \
          --account-name=${{ inputs.az-storage-account }} \
          --source=${{ inputs.az-storage-container }} \
          --if-unmodified-since $DELETE_DATE \
          '--pattern=*.js,*.css' 