name: "Cleanup Directory"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  az-subscription-id:
    description: "ID for subscription"
    required: true
  az-storage-account:
    description: "Azure Blob Storage account name"
    required: true
  az-storage-container:
    description: "Azure Blob Storage container name"
    default: "$web"
  file-retention-days:
    description: "How many days of js and css files we should keep"
    default: 10
  dryrun:
    description: "Print out what will be performed"
    default: true

runs:
  using: composite
  steps:
    - name: Delete old files from previous container (Dryrun)
      if: ${{ inputs.copy-from-previous-location && inputs.last-storage-account }}
      shell: bash
      run: |
        echo -e `date -v'-${{inputs.file-retention-days}}d' +%F'T'%H:%M'Z'` >> $DELETE_DATE
        az storage blob delete-batch \
          --account-name=${{ inputs.az-storage-account }} \
          '--container=${{ inputs.last-storage-container }}' \
          --source=${{ inputs.path }} \
          --delete-destination=${{ inputs.delete-destination }} \
          --if-unmodified-since $DELETE_DATE \
          '--pattern=*.js,*.css' \
          '--dryrun=${{ inputs.dryrun }} 
