name: "Purge Azure Front Door CDN Endpoint"
description: "Purges the Azure Front Door CDN endpoint using `az afd endpoint purge`"

inputs:
  resource-group:
    description: "Azure resource group name"
    required: true
  profile-name:
    description: "Azure Front Door profile name"
    required: true
  endpoint-name:
    description: "Azure Front Door endpoint name"
    required: true
  domains:
    description: "Space-separated list of domains to purge"
    required: true
  content-paths:
    description: "Space-separated list of content paths to purge"
    default: "/*"
  no-wait:
    description: "Whether to wait for the long-running operation to finish"
    default: false

runs:
  using: composite
  steps:
    - name: Purge endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "## Azure Frontdoor Endpoint Purge" >> $GITHUB_STEP_SUMMARY
          az afd endpoint purge \
            --resource-group ${{ inputs.resource-group }} \
            --profile-name ${{ inputs.profile-name }} \
            --endpoint-name ${{ inputs.endpoint-name }} \
            --domains ${{ inputs.domains }} \
            --content-paths ${{ inputs.content-paths }}
            --no-wait ${{ inputs.no-wait }} &&
            echo "Successfully purged CDN: \
              \`${{ inputs.profile-name }}/${{ inputs.endpoint-name }}\`" >> $GITHUB_STEP_SUMMARY ||
            echo "Failed to purge CDN: \
              \`${{ inputs.profile-name }}/${{ inputs.endpoint-name }}\`" >> $GITHUB_STEP_SUMMARY
