name: "Upload to Azure Storage"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  az-storage-account:
    description: 'Azure Blob Storage account name'
    required: true
  az-storage-container:
    description: 'Azure Blob Storage container name'
    default: "'$web'" # we have to quote this so the shell doesn't try to expand it
  paths:
    description: "File paths to upload"
    default: 'build'
  delete-destination:
    description: "Delete destination files not in source"
    default: 'true'
  cdn-base-name:
    description: 'Base name for CDN name and profile. Leave blank to skip purging CDN.'

runs: 
  using: composite
  steps:
    - name: Sync directories to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob sync \
            --account-name ${{ inputs.az-storage-account }} \
            --container ${{ inputs.az-storage-container }} \
            --source ${{ inputs.paths }} \
            --delete-destination ${{ inputs.delete-destination }} \
            | tee tmp_deploy_output.txt

    - name: Purge CDN endpoint
      if: ${{ inputs.cdn-base-name }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths "/*" --profile-name "${{ inputs.cdn-base-name }}-obama-org-CDN" --name "${{ inputs.cdn-base-name }}-obama-org" --resource-group "of-obama-org"

    - name: Print summary
      shell: bash
      run: |
        echo -e "## Deploy summary\n\n\`\`\`" >> $GITHUB_STEP_SUMMARY
        egrep 'Number of Copy Transfers|Total Number of Bytes' tmp_deploy_output.txt >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        [[ "${{ inputs.cdn-base-name }}" ]] \
          && (echo -e "## CDN purged: \`${{ inputs.cdn-base-name }}\`" >> $GITHUB_STEP_SUMMARY) \
          || (echo -e "## CDN not purged" >> $GITHUB_STEP_SUMMARY)
