name: "Upload to Azure Storage"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  az-subscription-id:
    description: "ID for subscription"
    required: true
  az-storage-account:
    description: "Azure Blob Storage account name"
    required: true
  last-storage-account:
    description: "Previous Azure Blob Storage account name if production"
    required: false
  copy-from-previous-location:
    description: If true, copy files from last-storage-account to az-storage-account
    default: "false"
  az-storage-container:
    description: "Azure Blob Storage container name"
    default: "$web"
  delete-destination:
    description: "Should delete files currently at the destination that do not appear in the current build"
    default: "true"
  
  path:
    description: "File path to upload"
    default: "build"

runs:
  using: composite
  steps:
    - name: Copy _app directory files
      shell: bash
      run: |
        az storage copy \
          '-s=${{ inputs.path }}/*' \
          '-d=https://${{ inputs.az-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          --subscription=${{ inputs.az-subscription-id }} \
          --recursive \
          '--include-path=_app' \
          | tee tmp_copy_output.txt

    - name: Copy html,xml,health-check files with no-store
      shell: bash
      run: |
        az storage copy \
          '-s=${{ inputs.path }}/*' \
          '-d=https://${{ inputs.az-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          --subscription=${{ inputs.az-subscription-id }} \
          --recursive \
          '--include-pattern=health-check;*.html;*.xml' \
          -- --cache-control=no-store \
          | tee tmp_copy_output.txt

    - name: Sync html files
      shell: bash
      run: |
        az storage blob sync \
          --account-name=${{ inputs.az-storage-account }} \
          '--container=${{ inputs.az-storage-container }}' \
          --source=${{ inputs.path }} \
          '--include-pattern=*.html' \
          | tee tmp_sync_output.txt

    - name: Sync remaining files
      shell: bash
      run: |
        az storage blob sync \
          --account-name=${{ inputs.az-storage-account }} \
          '--container=${{ inputs.az-storage-container }}' \
          --source=${{ inputs.path }} \
          --delete-destination=${{ inputs.delete-destination }} \
          | tee tmp_sync_output.txt

    - name: Copy _app directory files from previous container
      if: ${{ inputs.copy-from-previous-location && inputs.last-storage-account }}
      shell: bash
      run: |
        az storage copy \
          '-s=https://${{ inputs.last-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          '-d=https://${{ inputs.az-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          --subscription=${{ inputs.az-subscription-id }} \
          --recursive \
          '--include-path=_app' \
          | tee tmp_copy_output.txt

    - name: Print summary
      shell: bash
      run: |
        echo -e "## Azure storage upload\n\nCopy:\n\`\`\`" >> $GITHUB_STEP_SUMMARY
        egrep 'Number of Transfers|TotalBytesTransferred' tmp_copy_output.txt >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\n\nSync:\n\`\`\`" >> $GITHUB_STEP_SUMMARY
        egrep 'Number of Copy Transfers|Total Number of Bytes' tmp_sync_output.txt >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo -e "Deployment was successful: [https://${{ inputs.az-storage-account }}.z19.web.core.windows.net/](https://${{ inputs.az-storage-account }}.z19.web.core.windows.net/)\n" >> $GITHUB_STEP_SUMMARY
