name: "Upload to Azure Storage"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  az-storage-account:
    description: "Azure Blob Storage account name"
    required: true
  az-storage-container:
    description: "Azure Blob Storage container name"
    default: "'$web'" # we have to quote this so the shell doesn't try to expand it
  paths:
    description: "File paths to upload"
    default: "build"
  delete-destination:
    description: "Delete destination files not in source"
    default: "true"
  cdn-base-name:
    description: "(Deprecated) Base name for CDN name and profile. Leave blank to skip purging CDN."

runs:
  using: composite
  steps:
    - name: Sync directories to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob sync \
            --account-name ${{ inputs.az-storage-account }} \
            --container ${{ inputs.az-storage-container }} \
            --source ${{ inputs.paths }} \
            --delete-destination ${{ inputs.delete-destination }} \
            | tee tmp_deploy_output.txt

    - name: Purge CDN endpoint
      if: inputs.cdn-base-name
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "## Deprecation Warning" >> $GITHUB_STEP_SUMMARY
          echo "CDN purge is no longer handled by this module." >> $GITHUB_STEP_SUMMARY
          echo "See \`ObamaFoundation/actions/cdn-purge-classic\`" >> $GITHUB_STEP_SUMMARY


    - name: Print summary
      shell: bash
      run: |
        echo -e "## Azure storage upload\n\n\`\`\`" >> $GITHUB_STEP_SUMMARY
        egrep 'Number of Copy Transfers|Total Number of Bytes' tmp_deploy_output.txt >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
