name: "Upload to Azure Storage"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  deploy-prefix:
    description: 'Deploy prefix used for storage account and CDN'
    required: true
  az-storage-container:
    description: 'Azure Blob Storage container name'
    default: "'$web'" # we have to quote this so the shell doesn't try to expand it
  paths:
    description: "File paths to upload"
    default: 'build'
  delete-destination:
    description: "Delete destination files not in source"
    default: 'true'

runs: 
  using: composite
  steps:
  - name: Sync directories to blob storage
    uses: azure/CLI@v1
    with:
      inlineScript: |
        az storage blob sync \
          --account-name ${{ inputs.deploy-prefix }}obamaorg \
          --container ${{ inputs.az-storage-container }} \
          --source ${{ inputs.paths }} \
          --delete-destination ${{ inputs.delete-destination }}
  - name: Purge CDN endpoint
    uses: azure/CLI@v1
    with:
      inlineScript: |
        az cdn endpoint purge --content-paths "/*" --profile-name "${{ inputs.deploy-prefix }}-obama-org-CDN" --name "${{ inputs.deploy-prefix }}-obama-org" --resource-group "of-obama-org"
