name: "Upload to Azure Storage"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  az-storage-account:
    description: 'Azure Blob Storage account name'
    required: true
  az-storage-container:
    description: 'Azure Blob Storage container name'
    default: "$web"
  paths:
    description: "File paths to upload"
    default: 'build'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        script: |
          const script = require('./script.js')
          await script({core, exec})
