name: "Upload to Azure Storage"
description: "Uploads file paths to Azure Blob Storage using `sync`"

inputs:
  az-subscription-id:
    description: "ID for subscription"
    required: true
  az-storage-account:
    description: "Azure Blob Storage account name"
    required: true
  az-storage-container:
    description: "Azure Blob Storage container name"
    default: "$web"
  path:
    description: "File path to upload"
    default: "build"

runs:
  using: composite
  steps:
    - name: Copy html files with cache-control
      shell: bash
      run: |
        az storage copy \
          '-s=${{ inputs.path }}/*' \
          '-d=https://${{ inputs.az-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          --subscription=${{ inputs.az-subscription-id }} \
          --recursive \
          '--include-pattern=*.html' \
          -- --cache-control=no-store \
          | tee tmp_copy_output.txt
    - name: Copy immutable application files with long TTL values
      shell: bash
      run: |
        az storage copy \
          '-s=${{ inputs.path }}/_app/immutable/*' \
          '-d=https://${{ inputs.az-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          --subscription=${{ inputs.az-subscription-id }} \
          --recursive \
          -- --cache-control=max-age=31536000 \
          | tee tmp_copy-other_output.txt
      
    - name: Copy font files with long TTL values
      shell: bash
      run: |
        az storage copy \
          '-s=${{ inputs.path }}/fonts/*' \
          '-d=https://${{ inputs.az-storage-account }}.blob.core.windows.net/${{ inputs.az-storage-container }}' \
          --subscription=${{ inputs.az-subscription-id }} \
          --recursive \
          -- --cache-control=max-age=31536000 \
          | tee tmp_copy-other_output.txt
    - name: Sync remaining files
      shell: bash
      run: |
        az storage blob sync \
          --account-name=${{ inputs.az-storage-account }} \
          '--container=${{ inputs.az-storage-container }}' \
          --source=${{ inputs.path }} \
          | tee tmp_sync_output.txt

    - name: Print summary
      shell: bash
      run: |
        echo -e "## Azure storage upload\n\nCopy:\n\`\`\`" >> $GITHUB_STEP_SUMMARY
        egrep 'Number of Transfers|TotalBytesTransferred' tmp_copy_output.txt >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\n\nSync:\n\`\`\`" >> $GITHUB_STEP_SUMMARY
        egrep 'Number of Copy Transfers|Total Number of Bytes' tmp_sync_output.txt >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        echo -e "Deployment was successful: [https://${{ inputs.az-storage-account }}.z19.web.core.windows.net/](https://${{ inputs.az-storage-account }}.z19.web.core.windows.net/)\n" >> $GITHUB_STEP_SUMMARY
