name: "Deploy Preview"
description: "Deploys the preview app to Azure."
inputs:
  deploy-prefix:
    description: 'Deployment prefix'
    required: true
  azure-client-id:
    description: 'Azure client ID'
    required: true
  azure-client-secret:
    description: 'Azure client secret'
    required: true
  azure-subscription-id:
    description: 'Azure subscription ID'
    required: true
  azure-tenant-id:
    description: 'Azure tenant ID'
    required: true
  purge-cdn:
    description: 'Whether to purge the CDN'
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ inputs.azure-client-id }}","clientSecret":"${{ inputs.azure-client-secret }}","subscriptionId":"${{ inputs.azure-subscription-id }}","tenantId":"${{ inputs.azure-tenant-id }}"}'

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob sync \
            --account-name ${{ inputs.deploy-prefix }}obamaorg \
            --container '$web' \
            --source build \
            --delete-destination true

    - name: Purge CDN endpoint
      if: ${{ fromJSON(inputs.purge-cdn) }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths "/*" --profile-name "${{ inputs.deploy-prefix }}-obama-org-CDN" --name "${{ inputs.deploy-prefix }}-obama-org" --resource-group "of-obama-org"

    - name: Azure Logout
      if: always()
      shell: bash
      run: az logout
