name: "Zip and Upload Artifact"
description: "Zips files and uploads the result as a GitHub Actions artifact."
inputs:
  artifact-name:
    description: "Artifact name"
    required: true
  zip-name:
    description: "Name of the zip file"
    default: "build.zip"
  retention-days:
    description: "Duration after which artifact will expire in days"
    default: "0" # Defaults to repo default value
  paths:
    description: "File paths to zip"
    required: true
runs:
  using: "composite"
  steps:
    - run: mkdir -p tmp
      shell: bash
    - run: zip -rq tmp/${{ inputs.zip-name }} ${{ inputs.paths }}
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: tmp/${{ inputs.zip-name }}
        retention-days: ${{ inputs.retention-days }}
