name: "Publish to Chromatic"
description: "Publishes site to Chromatic"
inputs:
  chromatic-project-token:
    required: true
    description: "String - project auth token for chromatic"
  auto-accept-changes:
    required: false
    default: 'false'
    description: "boolean - whether or not the action tool should auto accept regressions"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci --legacy-peer-deps=true

    - name: Publish to Chromatic
      id: chromatic
      uses: chromaui/action@v1
      with:
        projectToken: ${{ inputs.chromatic-project-token }}
        buildScriptName: build:storybook
        exitZeroOnChanges: true
        onlyChanged: true
        exitOnceUploaded: true
        autoAcceptChanges: ${{ inputs.AUauto-accept-changes }}

    - name: Publish Summary
      shell: bash
      run: echo -e "| Results |  |\n| --- | --- |\n| Build Results | ${{steps.chromatic.outputs.buildUrl}} |\n| Storybook Preview | ${{steps.chromatic.outputs.storybookUrl}} |\n| Error Count | ${{steps.chromatic.outputs.errorCount}} |" >> $GITHUB_STEP_SUMMARY
