name: "Test Upload Download"

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: test-upload-download
  cancel-in-progress: true

jobs:
  test-upload-download:
    name: Upload and download
    runs-on: ubuntu-latest
    env:
      artifact_name: test-upload-download-${{ github.run_id }}
    steps:
      - name: Create test files
        shell: bash
        run: >
          mkdir testfiles &&
          echo "test data" > testfiles/file1 &&
          echo "more test data" > testfiles/file2
      - uses: ./upload-artifact-zip
        with:
          artifact-name: ${{ env.artifact_name }}
          paths: testfiles
          retention-days: 1
      - name: Rename test files
        shell: bash
        run: mv testfiles testfiles.org
      - uses: ./download-artifact-zip
        id: download
        with:
          artifact-name: ${{ env.artifact_name }}
      - name: Verify output variable
        if: steps.download.outputs.exists == 'false'
        shell: bash
        run: echo 'Exists output value should be true'; false
      - name: Verify test files
        shell: bash
        run: diff -r testfiles.org testfiles

  test-artifact-missing:
    name: Artifact does not exist
    runs-on: ubuntu-latest
    steps:
      - uses: ./download-artifact-zip
        id: download
        with:
          artifact-name: artifact-does-not-exist
      - name: Verify output variable
        if: steps.download.outputs.exists == 'true'
        shell: bash
        run: echo 'Exists output value should be false'; false
