name: "Test Custom Actions"

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-compile:
    name: Test compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - run: npm run test
  test-upload-download:
    name: Upload and download
    runs-on: ubuntu-latest
    env:
      artifact_name: test-upload-download-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Create test files
        shell: bash
        run: >
          mkdir testfiles &&
          echo "test data" > testfiles/file1 &&
          echo "more test data" > testfiles/file2
      - uses: ./upload-artifact-zip
        with:
          artifact-name: ${{ env.artifact_name }}
          paths: testfiles
          retention-days: 1
      - name: Rename test files
        shell: bash
        run: mv testfiles testfiles.org
      - uses: ./download-artifact-zip
        id: download
        with:
          artifact-name: ${{ env.artifact_name }}
      - name: Verify output variable
        if: steps.download.outputs.exists == 'false'
        shell: bash
        run: echo 'Exists output value should be true'; false
      - name: Verify test files
        shell: bash
        run: diff -r testfiles.org testfiles

  test-artifact-missing:
    name: Artifact does not exist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./download-artifact-zip
        id: download
        with:
          artifact-name: artifact-does-not-exist
      - name: Verify output variable
        if: steps.download.outputs.exists == 'true'
        shell: bash
        run: echo 'Exists output value should be false'; false

  test-health-check:
    name: Health check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./health-check
        with:
          endpoint: https://www.example.com
